name: "Build"

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    env:
      API: 24
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: true
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27d
      - name: Configure Android toolchain
        run: |
          export TOOLCHAIN=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64

          echo "CC=$TOOLCHAIN/bin/aarch64-linux-android${API}-clang" >> $GITHUB_ENV
          echo "CXX=$TOOLCHAIN/bin/aarch64-linux-android${API}-clang++" >> $GITHUB_ENV
          echo "AR=$TOOLCHAIN/bin/llvm-ar" >> $GITHUB_ENV
          echo "RANLIB=$TOOLCHAIN/bin/llvm-ranlib" >> $GITHUB_ENV
          echo "STRIP=$TOOLCHAIN/bin/llvm-strip" >> $GITHUB_ENV
      - name: Build
        run: |
          make \
            CC="$CC" \
            AR="$AR" \
            RANLIB="$RANLIB" \
            STRIP="$STRIP" \
            -j$(nproc)
      - name: Verify
        run: |
          file bin/hev-socks5-tunnel
          readelf -h bin/hev-socks5-tunnel | grep Machine
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: hev-socks5-tunnel-android-arm64-v8a
          path: bin/hev-socks5-tunnel
          if-no-files-found: error
          retention-days: 1
